[package]
name = "sentinel"
version = "0.1.0"
edition = "2021"

[dependencies]
configparser = "3"
walkdir = "2"

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"